spring:
    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
    h2:
        console:
            path: /h2
            enabled: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher